backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"     # cartella nel repo dove finiscono le immagini
public_folder: "/images/uploads"       # percorso pubblico nel sito generato

media_library:
  name: "uploadcare"

collections:
  - name: "posts"                      # nome tecnico
    label: "Articoli"                  # etichetta che vedrà Silvia
    folder: "src/posts"                # cartella dove stanno i .md
    create: true                       # può creare nuovi articoli
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"

      - label: "Data"
        name: "date"
        widget: "datetime"

      - label: "Bozza"
        name: "draft"
        widget: "boolean"
        default: true

      - label: "Contenuto"
        name: "body"
        widget: "markdown"
