backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"     # dove finiranno i file nel repo
public_folder: "/images/uploads"       # percorso pubblico nel sito generato

collections:
  - name: "posts"
    label: "Articoli"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"

      - label: "Data"
        name: "date"
        widget: "datetime"

      - label: "Bozza"
        name: "draft"
        widget: "boolean"
        default: true

      - label: "Contenuto"
        name: "body"
        widget: "markdown"
